import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { AboutComponent } from './pages/about/about.component';
import { ContactComponent } from './pages/contact/contact.component';
import { ServiceDetailComponent } from './pages/service-detail/service-detail.component';
import { PricingComponent } from './pages/pricing/pricing.component';
import { BankDetailsComponent } from './pages/bank-details/bank-details.component';
import { ConsentComponent } from './pages/consent/consent.component';
import { PrivacyPolicyComponent } from './pages/privacy-policy/privacy-policy.component';
import { TermsConditionsComponent } from './pages/terms-conditions/terms-conditions.component';
import { RefundPolicyComponent } from './pages/refund-policy/refund-policy.component';
import { DisclaimerComponent } from './pages/disclaimer/disclaimer.component';
import { DisclosureComponent } from './pages/disclosure/disclosure.component';
import { GrievanceComponent } from './pages/grievance/grievance.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'services/:slug', component: ServiceDetailComponent },
  { path: 'pricing', component: PricingComponent },
  { path: 'pricing/:tier', component: PricingComponent },
  { path: 'bank-details', component: BankDetailsComponent },
  { path: 'consent', component: ConsentComponent },
  { path: 'privacy-policy', component: PrivacyPolicyComponent },
  { path: 'terms-conditions', component: TermsConditionsComponent },
  { path: 'refund-policy', component: RefundPolicyComponent },
  { path: 'disclaimer', component: DisclaimerComponent },
  { path: 'disclosure', component: DisclosureComponent },
  { path: 'grievance', component: GrievanceComponent },
  { path: '**', redirectTo: '' }
];
